[package]
name = "dispatch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
dispatch-client = { workspace = true }
dispatch-core = { workspace = true }
dispatch-config = { workspace = true }
dispatch-layout = { workspace = true }
dispatch-os = { workspace = true }
dispatch-proto = { workspace = true }
dispatch-pty = { workspace = true }
dispatch-tui = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
dispatch-os = { workspace = true }
dispatch-pty = { workspace = true }
dispatch-config = { workspace = true }
dispatch-tui = { workspace = true }
toml = { workspace = true }
